apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: convert
  name: convert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convert
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: convert
    spec:
      containers:
      - args:
         - "--countryCodes=IN"
        image: prashanthmanohr/sony:2
        imagePullPolicy: IfNotPresent
        name: convert
      imagePullSecrets:
      - name: regcred
