apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: diag
spec:
  jobTemplate:
    metadata:
      name: diag
    spec:
      template:
        metadata:
          labels:
            app: diag
        spec:
          containers:
            - name: diag
              image: odaniait/aws-kubectl:latest
              command:
              - /bin/sh
              - "-c"
              - |-
                echo "Checking health"
                value=$(curl -s -o /dev/null -w ''%{http_code}'' https://www.travel-advisory.info/api)
                if [[ "$value" == 200 ]];then
                echo "Service is up"
                else
                echo "Service is down"
                fi
          restartPolicy: Never
  schedule: "*/1 * * * *"
