apiVersion: v1
kind: Service
metadata:
  name: diag
spec:
  type: ClusterIP
  selector:
    app: diag
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: diag
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: diag
  template: 
    metadata: 
      labels: 
        app: diag
    spec: 
      containers: 
        - "command - /bin/sh - -c - |- curl -I -s -L https://www.travel-advisory.info/api | grep \"HTTP/2\""
